"""Generate reference trajectories for the core physics tests.

Reference: py-ballisticcalc (LGPL-3.0) SciPy engine, DOP853 with very tight
tolerances, i.e. an independent, near-exact solution of the same
point-mass equations. Two settings are aligned with bal_calc so that the
comparison isolates the integrator and drag model:

* speed of sound uses the dry-air formula (bal_calc SoundSpeedModel::kDryAir);
* py-ballisticcalc's "within 30 ft of the base altitude, reuse base air"
  shortcut is disabled, so air is always evaluated at the actual altitude.

Usage (needs py_ballisticcalc and scipy on PYTHONPATH):
    python generate_reference.py > reference_trajectories.inc
"""

import math

from py_ballisticcalc import (
    Ammo, Atmo, Calculator, Distance, DragModel, Pressure, Shot, Temperature,
    Velocity, Weapon, Weight, TableG1, TableG7, Angular, loadMetricUnits,
)
from py_ballisticcalc.conditions import Atmo as AtmoCls
from py_ballisticcalc.constants import cDegreesCtoK, cLapseRateKperFoot

loadMetricUnits()


def _air_at_altitude(self, altitude):
    t_k = self.temperature_at_altitude(altitude) + cDegreesCtoK
    mach = Velocity.MPS(AtmoCls.machK(t_k)) >> Velocity.FPS
    p = self.pressure_at_altitude(altitude)
    density_delta = ((self._t0 + cDegreesCtoK) * p) / (self._p0 * t_k)
    return self._density_ratio * density_delta, mach


AtmoCls.get_density_and_mach_for_altitude = _air_at_altitude

ENGINE_CONFIG = {
    "integration_method": "DOP853",
    "relative_tolerance": 1e-12,
    "absolute_tolerance": 1e-12,
    "cMinimumVelocity": 0.0,
}

# name, table, bc, grains, diameter in, length in, v0 m/s, sight cm, zero m,
# max range m, step m
CARTRIDGES = [
    ("308_175smk_g7", "G7", 0.243, 175.0, 0.308, 1.240, 800.0, 5.0, 100.0, 2500.0, 100.0),
    ("65cm_140eldm_g7", "G7", 0.326, 140.0, 0.264, 1.370, 823.0, 4.5, 100.0, 2500.0, 100.0),
    ("338lm_300hybrid_g7", "G7", 0.419, 300.0, 0.338, 1.700, 838.0, 5.5, 100.0, 2500.0, 100.0),
    ("50bmg_750amax_g1", "G1", 1.050, 750.0, 0.510, 2.420, 860.0, 7.0, 100.0, 2500.0, 100.0),
    ("556_m855_g1", "G1", 0.304, 62.0, 0.224, 0.906, 930.0, 6.5, 100.0, 1000.0, 50.0),
]

# name, altitude m, pressure hPa (station), temperature C, humidity 0..1
ATMOSPHERES = [
    ("icao", 0.0, 1013.25, 15.0, 0.0),
    ("mountain_cold_humid", 1500.0, 850.0, -10.0, 0.5),
    ("hot_humid", 200.0, 990.0, 35.0, 0.9),
]

LOOK_ANGLES_DEG = [0.0, 20.0]


def main():
    calc = Calculator(engine="scipy_engine", config=ENGINE_CONFIG)
    print("// Generated by generate_reference.py - do not edit by hand.")
    print("// {case, atmosphere, look angle deg, zero elevation rad, points{slant m, drop m, speed m/s, time s}}")
    for (name, table, bc, gr, dia, length, v0, sight_cm, zero_m, max_m, step_m) in CARTRIDGES:
        for (aname, alt, p_hpa, t_c, rh) in ATMOSPHERES:
            for look in LOOK_ANGLES_DEG:
                dm = DragModel(bc, TableG7 if table == "G7" else TableG1, Weight.Grain(gr),
                               Distance.Inch(dia), Distance.Inch(length))
                ammo = Ammo(dm, Velocity.MPS(v0))
                weapon = Weapon(Distance.Centimeter(sight_cm))
                atmo = Atmo(Distance.Meter(alt), Pressure.hPa(p_hpa), Temperature.Celsius(t_c), rh)
                # Zero at the same conditions, level.
                zero_shot = Shot(weapon=weapon, ammo=ammo, atmo=atmo)
                zero_angle = float(calc.set_weapon_zero(zero_shot, Distance.Meter(zero_m)) >> Angular.Radian)
                # Inclined shots: bal_calc keeps the sight perpendicular to
                # the LOS, py-ballisticcalc vertically above the bore, so
                # compare them without a sight offset (same zero angle).
                if look != 0.0:
                    weapon = Weapon(Distance.Centimeter(0.0), zero_elevation=Angular.Radian(zero_angle))
                shot = Shot(weapon=weapon, ammo=ammo, atmo=atmo,
                            look_angle=Angular.Degree(look))
                res = calc.fire(shot, Distance.Meter(max_m / math.cos(math.radians(look)) + 50.0),
                                Distance.Meter(10.0), dense_output=True)
                rows = []
                k = 1
                while k * step_m <= max_m + 1e-9:
                    slant = k * step_m
                    pt = res.get_at("slant_distance", Distance.Meter(slant))
                    rows.append((slant, float(pt.slant_height >> Distance.Meter),
                                 float(pt.velocity >> Velocity.MPS), float(pt.time)))
                    k += 1
                print(f'{{"{name}", "{aname}", {look!r}, {zero_angle!r}, {{')
                for (s, h, v, t) in rows:
                    print(f"    {{{s!r}, {h!r}, {v!r}, {t!r}}},")
                print("}},")


if __name__ == "__main__":
    main()
