"""Generate reference trajectories for the core physics tests.

Reference: py-ballisticcalc (LGPL-3.0) SciPy engine, DOP853 with very tight
tolerances, i.e. an independent, near-exact solution of the same
point-mass equations. Two settings are aligned with bal_calc so that the
comparison isolates the integrator and drag model:

* speed of sound uses the dry-air formula (bal_calc SoundSpeedModel::kDryAir);
* py-ballisticcalc's "within 30 ft of the base altitude, reuse base air"
  shortcut is disabled, so air is always evaluated at the actual altitude.

Usage (needs py_ballisticcalc and scipy on PYTHONPATH):
    python generate_reference.py > reference_trajectories.inc
    python generate_reference.py effects > reference_effects.inc
    python generate_reference.py multibc > reference_multibc.inc

The "effects" set adds wind zones, Coriolis/Eotvos and spin drift
(level fire, standard drag). bal_calc's wind direction is where the wind
blows FROM, clockwise from the line of fire with 0 = headwind;
py-ballisticcalc's 0 = tailwind, hence the 180 degree shift below.
"""

import sys

import math

from py_ballisticcalc import (
    BCPoint, DragModelMultiBC, Ammo, Atmo, Calculator, Distance, DragModel, Pressure, Shot, Temperature,
    Velocity, Weapon, Weight, Wind, TableG1, TableG7, Angular, loadMetricUnits,
)
from py_ballisticcalc.conditions import Atmo as AtmoCls
from py_ballisticcalc.constants import cDegreesCtoK, cLapseRateKperFoot

loadMetricUnits()


def _air_at_altitude(self, altitude):
    t_k = self.temperature_at_altitude(altitude) + cDegreesCtoK
    mach = Velocity.MPS(AtmoCls.machK(t_k)) >> Velocity.FPS
    p = self.pressure_at_altitude(altitude)
    density_delta = ((self._t0 + cDegreesCtoK) * p) / (self._p0 * t_k)
    return self._density_ratio * density_delta, mach


AtmoCls.get_density_and_mach_for_altitude = _air_at_altitude

ENGINE_CONFIG = {
    "integration_method": "DOP853",
    "relative_tolerance": 1e-12,
    "absolute_tolerance": 1e-12,
    "cMinimumVelocity": 0.0,
}

# name, table, bc, grains, diameter in, length in, v0 m/s, sight cm, zero m,
# max range m, step m
CARTRIDGES = [
    ("308_175smk_g7", "G7", 0.243, 175.0, 0.308, 1.240, 800.0, 5.0, 100.0, 2500.0, 100.0),
    ("65cm_140eldm_g7", "G7", 0.326, 140.0, 0.264, 1.370, 823.0, 4.5, 100.0, 2500.0, 100.0),
    ("338lm_300hybrid_g7", "G7", 0.419, 300.0, 0.338, 1.700, 838.0, 5.5, 100.0, 2500.0, 100.0),
    ("50bmg_750amax_g1", "G1", 1.050, 750.0, 0.510, 2.420, 860.0, 7.0, 100.0, 2500.0, 100.0),
    ("556_m855_g1", "G1", 0.304, 62.0, 0.224, 0.906, 930.0, 6.5, 100.0, 1000.0, 50.0),
]

# name, altitude m, pressure hPa (station), temperature C, humidity 0..1
ATMOSPHERES = [
    ("icao", 0.0, 1013.25, 15.0, 0.0),
    ("mountain_cold_humid", 1500.0, 850.0, -10.0, 0.5),
    ("hot_humid", 200.0, 990.0, 35.0, 0.9),
]

LOOK_ANGLES_DEG = [0.0, 20.0]


def main():
    calc = Calculator(engine="scipy_engine", config=ENGINE_CONFIG)
    print("// Generated by generate_reference.py - do not edit by hand.")
    print("// {case, atmosphere, look angle deg, zero elevation rad, points{slant m, drop m, speed m/s, time s}}")
    for (name, table, bc, gr, dia, length, v0, sight_cm, zero_m, max_m, step_m) in CARTRIDGES:
        for (aname, alt, p_hpa, t_c, rh) in ATMOSPHERES:
            for look in LOOK_ANGLES_DEG:
                dm = DragModel(bc, TableG7 if table == "G7" else TableG1, Weight.Grain(gr),
                               Distance.Inch(dia), Distance.Inch(length))
                ammo = Ammo(dm, Velocity.MPS(v0))
                weapon = Weapon(Distance.Centimeter(sight_cm))
                atmo = Atmo(Distance.Meter(alt), Pressure.hPa(p_hpa), Temperature.Celsius(t_c), rh)
                # Zero at the same conditions, level.
                zero_shot = Shot(weapon=weapon, ammo=ammo, atmo=atmo)
                zero_angle = float(calc.set_weapon_zero(zero_shot, Distance.Meter(zero_m)) >> Angular.Radian)
                # Inclined shots: bal_calc keeps the sight perpendicular to
                # the LOS, py-ballisticcalc vertically above the bore, so
                # compare them without a sight offset (same zero angle).
                if look != 0.0:
                    weapon = Weapon(Distance.Centimeter(0.0), zero_elevation=Angular.Radian(zero_angle))
                shot = Shot(weapon=weapon, ammo=ammo, atmo=atmo,
                            look_angle=Angular.Degree(look))
                res = calc.fire(shot, Distance.Meter(max_m / math.cos(math.radians(look)) + 50.0),
                                Distance.Meter(10.0), dense_output=True)
                rows = []
                k = 1
                while k * step_m <= max_m + 1e-9:
                    slant = k * step_m
                    pt = res.get_at("slant_distance", Distance.Meter(slant))
                    rows.append((slant, float(pt.slant_height >> Distance.Meter),
                                 float(pt.velocity >> Velocity.MPS), float(pt.time)))
                    k += 1
                print(f'{{"{name}", "{aname}", {look!r}, {zero_angle!r}, {{')
                for (s, h, v, t) in rows:
                    print(f"    {{{s!r}, {h!r}, {v!r}, {t!r}}},")
                print("}},")


# name, cartridge, atmosphere, twist in (+right, 0 none),
# winds [(until m, speed m/s, from deg in bal_calc convention)], latitude, azimuth
EFFECTS = [
    ("wind_right_4", "308_175smk_g7", "icao", 0.0, [(1e5, 4.0, 90.0)], None, None),
    ("wind_left_front_6", "308_175smk_g7", "icao", 0.0, [(1e5, 6.0, 300.0)], None, None),
    ("wind_zones", "308_175smk_g7", "mountain_cold_humid", 0.0,
     [(500.0, 3.0, 270.0), (1500.0, 5.0, 45.0), (1e5, 2.0, 135.0)], None, None),
    ("coriolis_n50_east", "338lm_300hybrid_g7", "icao", 0.0, [], 50.0, 90.0),
    ("coriolis_n50_north", "338lm_300hybrid_g7", "icao", 0.0, [], 50.0, 0.0),
    ("coriolis_s30_west", "338lm_300hybrid_g7", "icao", 0.0, [], -30.0, 270.0),
    ("coriolis_n60_sw", "50bmg_750amax_g1", "icao", 0.0, [], 60.0, 225.0),
    ("spin_right_10", "308_175smk_g7", "icao", 10.0, [], None, None),
    ("spin_left_8", "65cm_140eldm_g7", "hot_humid", -8.0, [], None, None),
    ("combined_338", "338lm_300hybrid_g7", "mountain_cold_humid", 9.4,
     [(800.0, 4.0, 80.0), (1e5, 6.0, 110.0)], 48.0, 135.0),
    ("combined_50", "50bmg_750amax_g1", "hot_humid", 15.0,
     [(1000.0, 5.0, 240.0), (1e5, 3.0, 20.0)], 35.0, 10.0),
]


def main_effects():
    calc = Calculator(engine="scipy_engine", config=ENGINE_CONFIG)
    carts = {c[0]: c for c in CARTRIDGES}
    atmos = {a[0]: a for a in ATMOSPHERES}
    print("// Generated by generate_reference.py effects - do not edit by hand.")
    print("// {case, zero elevation rad, points{slant m, drop m, windage m, speed m/s, time s}}")
    for (name, cname, aname, twist, winds, lat, az) in EFFECTS:
        (_, table, bc, gr, dia, length, v0, sight_cm, zero_m, max_m, step_m) = carts[cname]
        (_, alt, p_hpa, t_c, rh) = atmos[aname]
        dm = DragModel(bc, TableG7 if table == "G7" else TableG1, Weight.Grain(gr),
                       Distance.Inch(dia), Distance.Inch(length))
        ammo = Ammo(dm, Velocity.MPS(v0))
        weapon = Weapon(Distance.Centimeter(sight_cm), twist=Distance.Inch(twist))
        atmo = Atmo(Distance.Meter(alt), Pressure.hPa(p_hpa), Temperature.Celsius(t_c), rh)
        zero_angle = float(calc.set_weapon_zero(Shot(weapon=weapon, ammo=ammo, atmo=atmo),
                                                Distance.Meter(zero_m)) >> Angular.Radian)
        py_winds = [Wind(Velocity.MPS(sp), Angular.Degree((deg + 180.0) % 360.0), Distance.Meter(until))
                    for (until, sp, deg) in winds]
        shot = Shot(weapon=weapon, ammo=ammo, atmo=atmo, winds=py_winds, latitude=lat, azimuth=az)
        res = calc.fire(shot, Distance.Meter(max_m + 50.0), Distance.Meter(10.0), dense_output=True)
        print(f'{{"{name}", {zero_angle!r}, {{')
        k = 1
        while k * step_m <= max_m + 1e-9:
            pt = res.get_at("slant_distance", Distance.Meter(k * step_m))
            print(f"    {{{k * step_m!r}, {float(pt.slant_height >> Distance.Meter)!r}, "
                  f"{float(pt.windage >> Distance.Meter)!r}, {float(pt.velocity >> Velocity.MPS)!r}, "
                  f"{float(pt.time)!r}}},")
            k += 1
        print("}},")


# name, table, [(velocity m/s, bc)], grains, v0 m/s, sight cm, zero m, max m, step m
MULTIBC = [
    # Sierra 175gr SMK published G1 bands (.505 >2800 fps, .496 1800-2800, .485 <1800)
    ("smk175_sierra_g1", "G1", [(869.0, 0.505), (701.0, 0.496), (457.0, 0.485)],
     175.0, 800.0, 5.0, 100.0, 2000.0, 100.0),
    ("g7_two_points", "G7", [(800.0, 0.330), (400.0, 0.300)], 140.0, 823.0, 4.5, 100.0, 2500.0, 100.0),
]


def main_multibc():
    calc = Calculator(engine="scipy_engine", config=ENGINE_CONFIG)
    print("// Generated by generate_reference.py multibc - do not edit by hand.")
    print("// {case, zero elevation rad, points{slant m, drop m, speed m/s, time s}}")
    for (name, table, pts, gr, v0, sight_cm, zero_m, max_m, step_m) in MULTIBC:
        dm = DragModelMultiBC([BCPoint(bc, V=Velocity.MPS(v)) for (v, bc) in pts],
                              TableG7 if table == "G7" else TableG1)
        ammo = Ammo(dm, Velocity.MPS(v0))
        weapon = Weapon(Distance.Centimeter(sight_cm))
        atmo = Atmo.icao()
        zero_angle = float(calc.set_weapon_zero(Shot(weapon=weapon, ammo=ammo, atmo=atmo),
                                                Distance.Meter(zero_m)) >> Angular.Radian)
        res = calc.fire(Shot(weapon=weapon, ammo=ammo, atmo=atmo), Distance.Meter(max_m + 50.0),
                        Distance.Meter(10.0), dense_output=True)
        print(f'{{"{name}", {zero_angle!r}, {{')
        k = 1
        while k * step_m <= max_m + 1e-9:
            pt = res.get_at("slant_distance", Distance.Meter(k * step_m))
            print(f"    {{{k * step_m!r}, {float(pt.slant_height >> Distance.Meter)!r}, "
                  f"{float(pt.velocity >> Velocity.MPS)!r}, {float(pt.time)!r}}},")
            k += 1
        print("}},")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "multibc":
        main_multibc()
        sys.exit(0)
    if len(sys.argv) > 1 and sys.argv[1] == "effects":
        main_effects()
    else:
        main()
